-- Database: sound_soul

DROP DATABASE IF EXISTS sound_soul;

CREATE DATABASE sound_soul
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Mexico.1252'
    LC_CTYPE = 'Spanish_Mexico.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS sound.belong_pivot
(
    son_id bigint NOT NULL DEFAULT nextval('sound.belong_pivot_son_id_seq'::regclass),
    parent_id bigint NOT NULL DEFAULT nextval('sound.belong_pivot_parent_id_seq'::regclass),
    type_id bigint NOT NULL DEFAULT nextval('sound.belong_pivot_type_id_seq'::regclass),
    CONSTRAINT belong_unique_son_parent_type UNIQUE (son_id, parent_id, type_id)
);

CREATE TABLE IF NOT EXISTS sound.category
(
    id bigint NOT NULL DEFAULT nextval('sound.category_id_seq'::regclass),
    name character varying(15) COLLATE pg_catalog."default" NOT NULL,
    type_id bigint NOT NULL DEFAULT nextval('sound.category_type_id_seq'::regclass),
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT category_unique_name_type UNIQUE (name, type_id)
);

CREATE TABLE IF NOT EXISTS sound.creator
(
    id bigint NOT NULL DEFAULT nextval('sound.creator_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL DEFAULT '-'::text,
    cat_id bigint NOT NULL DEFAULT nextval('sound.creator_cat_id_seq'::regclass),
    fav boolean NOT NULL DEFAULT false,
    CONSTRAINT creator_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sound.credit_pivot
(
    med_id bigint NOT NULL DEFAULT nextval('sound.credit_pivot_med_id_seq'::regclass),
    create_id bigint NOT NULL DEFAULT nextval('sound.credit_pivot_create_id_seq'::regclass),
    CONSTRAINT credit_unique_med_create UNIQUE (med_id, create_id)
);

CREATE TABLE IF NOT EXISTS sound.entity_type
(
    id bigint NOT NULL DEFAULT nextval('sound.entity_type_id_seq'::regclass),
    name character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT entity_type_pkey PRIMARY KEY (id),
    CONSTRAINT type_unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS sound.excerpt
(
    id bigint NOT NULL DEFAULT nextval('sound.excerpt_id_seq'::regclass),
    excerpt text COLLATE pg_catalog."default" NOT NULL,
    med_id bigint NOT NULL DEFAULT nextval('sound.excerpt_med_id_seq'::regclass),
    CONSTRAINT excerpt_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sound.medium
(
    id bigint NOT NULL DEFAULT nextval('sound.medium_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    cat_id bigint NOT NULL DEFAULT nextval('sound.medium_cat_id_seq'::regclass),
    fav boolean NOT NULL DEFAULT false,
    CONSTRAINT medium_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS sound.belong_pivot
    ADD CONSTRAINT belong_type_fk FOREIGN KEY (type_id)
    REFERENCES sound.entity_type (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS sound.category
    ADD CONSTRAINT category_type_fk FOREIGN KEY (type_id)
    REFERENCES sound.entity_type (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS sound.creator
    ADD CONSTRAINT creator_category_fk FOREIGN KEY (cat_id)
    REFERENCES sound.category (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS sound.credit_pivot
    ADD CONSTRAINT credit_creator_fk FOREIGN KEY (create_id)
    REFERENCES sound.creator (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS sound.credit_pivot
    ADD CONSTRAINT credit_medium_fk FOREIGN KEY (med_id)
    REFERENCES sound.medium (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS sound.excerpt
    ADD CONSTRAINT excerpt_medium_fk FOREIGN KEY (med_id)
    REFERENCES sound.medium (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS sound.medium
    ADD CONSTRAINT medium_category_fk FOREIGN KEY (cat_id)
    REFERENCES sound.category (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

END;